# Generated by Django 5.1.1 on 2024-10-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('evidence', 'Evidence'), ('verification', 'Verification')], default='comment', max_length=50),
        ),
        migrations.AddField(
            model_name='contribution',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.investigation'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='core.report'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('in_progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.CreateModel(
            name='ContributionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contribution_evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.contribution')),
            ],
        ),
    ]
