# Generated by Django 5.1.1 on 2024-10-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_badge_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='case_reports/'),
        ),
        migrations.AddField(
            model_name='casereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('published', 'Published')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='contribution',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.report'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='core.report'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('in_progress', 'In Progress'), ('Closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.investigation')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead Investigator'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer')], default='contributor', max_length=50)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.investigation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('investigation', 'user')},
            },
        ),
    ]
